[book]
authors = ["toj900"]
language = "en"
multilingual = false
src = "src"
title = "Guidelines"

[output.html]
no-section-label = true
additional-css = ["theme/css/custom.css"]

[output.html.playground]
line-numbers = false
runnable = false
